name: Commit solution and create new branch

on:
 workflow_dispatch:
  inputs:
   solution-name:
    required: true
   commit-message:
    required: true
    
jobs:

 export-commit-solution:
  environment: Dev environment
  runs-on: ubuntu-latest
  
  steps:
   - uses: actions/checkout@v3
   - uses: microsoft/powerplatform-actions/export-solution@v0
     with:
      environment-url: ${{ secrets.ENVIRONMENT_URL }}
      app-id: ${{ secrets.CLIENT_ID }}
      client-secret: ${{ secrets.CLIENT_SECRET }}
      tenant-id: ${{ secrets.TENANT_ID }}
      solution-name: ${{ github.event.inputs.solution-name }}
      solution-output-file: ${{ github.event.inputs.solution-name }}.zip
   - uses: microsoft/powerplatform-actions/export-solution@v0
     with:
      environment-url: ${{ secrets.ENVIRONMENT_URL }}
      app-id: ${{ secrets.CLIENT_ID }}
      client-secret: ${{ secrets.CLIENT_SECRET }}
      tenant-id: ${{ secrets.TENANT_ID }}
      solution-name: ${{ github.event.inputs.solution-name }}
      solution-output-file: ${{ github.event.inputs.solution-name }}_managed.zip
      managed: true
   - name: Clear existing folder
     run: |
       rm -rf solutions/${{ github.event.inputs.solution-name }}/src
     shell: bash
   - uses: microsoft/powerplatform-actions/unpack-solution@v0
     with:
      solution-file: ${{ github.event.inputs.solution-name }}.zip
      solution-folder: solutions/${{ github.event.inputs.solution-name }}/src
      solution-type: Both
   - name: branch-solution, prepare it for a PullRequest
     uses: microsoft/powerplatform-actions/branch-solution@v0
     with:
      solution-folder: solutions/${{ github.event.inputs.solution-name }}/src
      solution-target-folder: solutions/branch/${{ github.event.inputs.solution-name }}/src
      repo-token: ${{ secrets.GITHUB_TOKEN }}
      allow-empty-commit: true
      
       

   
  
  
