name: Deploy idea management

on:
  workflow_dispatch:
    inputs:
      deploy-creatorkit:
        type: boolean
      target-environment:
        required: true
        type: environment

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: packed-solutions/connector/AIServicesconnector.zip
          solution-folder: solutions/AIServicesconnector/src
          solution-type: Both
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: packed-solutions/idea-management/IdeaManagement.zip
          solution-folder: solutions/IdeaManagement/src
          solution-type: Both
      - if: ${{ github.event.inputs.deploy-creatorkit == 'true' }}
        name: Download Creator Kit
        run: |
          curl -L -o packed-solutions/creatorkit/creatorkit.zip https://aka.ms/creatorkitdownload
      - uses: actions/upload-artifact@v3
        with:
          name: packed-solutions
          path: packed-solutions

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target-environment }}
    needs: [build]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: packed-solutions
      - if: ${{ github.event.inputs.deploy-creatorkit == 'true' }}
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ secrets.ENVIRONMENT_URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-file: creatorkit/creatorkit.zip
      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ secrets.ENVIRONMENT_URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-file: connector/AIServicesconnector_managed.zip
          deployment-settings-file: deployment-files/env-variables-connector.json
